<!DOCTYPE html>
<html>
    <head>
        <title>Geolocation</title>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
        <meta charset="utf-8">

        <style>
            html, body {
                height: 100%;
                margin: 0;
                padding: 0;
            }
            #map {
                height: 100%;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    </head>
    <body>
        <div id="map"></div>
        
        <script>
            // Note: This example requires that you consent to location sharing when
            // prompted by your browser. If you see the error "The Geolocation service
            // failed.", it means you probably did not give permission for the browser to
            // locate you.

            var marker;


            function handleLocationError(browserHasGeolocation, infoWindow, pos) {
                infoWindow.setPosition(pos);
                infoWindow.setContent(browserHasGeolocation ?
                        'Error: The Geolocation service failed.' :
                        'Error: Your browser doesn\'t support geolocation.');
            }

            function initMap() {
//                while(window.pos){
//                    console.log("Loading...")
//                }

                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 19,
                    center: {lat: 59.325, lng: 18.070}
                });


                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: {lat: 59.327, lng: 18.067}
                });
                marker.addListener('click', toggleBounce);
                google.maps.event.addListener(marker, 'dragend', function(evt) {
                    $("[name=lat]",window.parent.document.body).val(evt.latLng.lat() );
                    $("[name=lng]",window.parent.document.body).val(evt.latLng.lng());
//                    $("[name=okposition]",window.parent.document.body).prop('checked', true);
//                    alert(  '<p>Marker dropped: Current Lat: ' + evt.latLng.lat() + ' Current Lng: ' + evt.latLng.lng()+ '</p>');
                });

                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function(position) {
                        pos = {
                            lat: position.coords.latitude,
                            lng: position.coords.longitude
                        };
                        map.setCenter(pos);
                        marker.setPosition(pos);

                    }, function() {
                        handleLocationError(true, infoWindow, map.getCenter());
                    });
                } else {
                    // Browser doesn't support Geolocation
                    handleLocationError(false, infoWindow, map.getCenter());
                }
            }

            function toggleBounce() {
                
                if (marker.getAnimation() !== null) {
                    marker.setAnimation(null);
                } else {
                    marker.setAnimation(google.maps.Animation.BOUNCE);
                }
            }

        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDXdo3_TI0k2l1OfCGQMtDE2k1eHwcI6Ro&callback=initMap"
                async defer>
        </script>
    </body>
</html>