<?php $this->crearTabla($this->params[tipo_descuento],array(),"Tipos descuento",array('urlConsultar' => "administrador/registrarTipoDescuento", 
                'urlAjax' => "administrador/registrarTipoDescuento",
            'create' => 'administrador/registrarTipoDescuento'))?>
<?php // $this->crearTabla($this->params[tipo_descuento],array(),"Tipos descuento","administrador/registrarTipoDescuento","administrador/registrarTipoDescuento")?>