
<label for="cotizacion">Cotización :</label>
<select class="form-control" id="cotizacion" name="cotizacion" title="Ingrese cotizacion">
    <option value="">Seleccione</option>
</select>
<br/><br/>
Agregar productos
<br/><br/>
<table class="table table-hover">
    <thead>
        <tr>
            <th><span class="glyphicon glyphicon-plus"></span>&nbsp;


                </th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Descuento</th>
        </tr>
    </thead>
    <tbody>

        <tr><td>	<div class="btn-group" data-toggle="buttons">		<label class="btn btn-success active">
                    <input type="checkbox" autocomplete="off" checked>
                    <span class="glyphicon glyphicon-ok"></span>
                </label>
                </div>
            </td>
            <td>
                <select class="form-control" id="idCategoria" name="idCategoria" title="Ingrese producto">
                    <option value="">Seleccione</option>
                </select>
            </td>
            <td><input title="Palabras clave" type="number" class="form-control" id="keyWords" name="keyWords"></td>
            <td><label>%10</label></td>
        </tr>
        <tr>
            <td>		<div class="btn-group" data-toggle="buttons">		<label class="btn btn-success active">
                    <input type="checkbox" autocomplete="off" checked>
                    <span class="glyphicon glyphicon-ok"></span>
                </label>
                </div></td>
            <td>
                <select class="form-control" id="idCategoria" name="idCategoria" title="Ingrese producto">
                    <option value="">Seleccione</option>
                </select>
            </td>
            <td><input title="Palabras clave" type="number" class="form-control" id="keyWords" name="keyWords"></td>
            <td><label>%10</label></td>
        </tr>
        <tr><td>	<div class="btn-group" data-toggle="buttons">		<label class="btn btn-success active">
                    <input type="checkbox" autocomplete="off" checked>
                    <span class="glyphicon glyphicon-ok"></span>
                </label>
                </div></td>
            <td>
                <select class="form-control" id="idCategoria" name="idCategoria" title="Ingrese producto">
                    <option value="">Seleccione</option>
                </select>
            </td>
            <td><input title="Palabras clave" type="number" class="form-control" id="keyWords" name="keyWords"></td>
            <td><label>%10</label></td>
        </tr>
        <tr>
            <td colspan="2">

            </td>
            <td><b>Costo total</b></td>
            <td>$$$$$</td>
        </tr>
        <tr>
            <td>

            </td>
            <td><b>Descuento</b></td>
            <td>$$$$$</td>
        </tr>
        <tr>
            <td>

            </td>
            <td><b>Valor real</b></td>
            <td>$$$$$</td>
        </tr>
</table>
<div class="form-group">
    <label for="observacion">Observación:</label>
    <textarea class="form-control" rows="4" id="observacion"></textarea>
</div>


<button >Guardar</button>
